/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as ApiSubtitlesRouteImport } from './app/routes/api/subtitles'
import { Route as ApiDownloadRouteImport } from './app/routes/api/download'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubtitlesRoute = ApiSubtitlesRouteImport.update({
  id: '/api/subtitles',
  path: '/api/subtitles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/subtitles': typeof ApiSubtitlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/subtitles': typeof ApiSubtitlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/subtitles': typeof ApiSubtitlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/download' | '/api/subtitles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/download' | '/api/subtitles'
  id: '__root__' | '/' | '/api/download' | '/api/subtitles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiSubtitlesRoute: typeof ApiSubtitlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subtitles': {
      id: '/api/subtitles'
      path: '/api/subtitles'
      fullPath: '/api/subtitles'
      preLoaderRoute: typeof ApiSubtitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiSubtitlesRoute: ApiSubtitlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
